name: Check Non-ASCII Character
author: Codevience
description: Check the files and directories name and content exist non ASCII.

inputs:
  gh_token:
    description: "Github Personal Access token"
    required: False

runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/action.py 
      shell: bash

branding:
  icon: 'info'
  color: 'cyan'